---

ssh_source_key: ~/ansible-macos-playbook/roles/ssh/.ssh/id_rsa
ssh_dest_key: ~/.ssh/id_rsa

computername: sse
hostname: sse

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: no
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: yes
system_index_network_storage_with_spotlight: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts

homebrew_apps:
  - bitwarden
  - brave-browser
  - cheatsheet
  - chromium
  - clipy
  - discord
  - docker
  - firefox
  - free-ruler
  - google-chrome
  - iterm2
  - jetbrains-toolbox
  - keka
  - notion
  - rectangle # successor of spectacle
  - skype
  - slack
  - telegram
  - tor-browser
  - vlc
  - vscodium

homebrew_packages:
  - curl
  - fasd
  - fzf
  - git
  - httpie
  - make
  - mas
  - neovim
  - n
  - openssh
  - python
  - reattach-to-user-namespace
  - stow
  - tldr
  - tmux
  - tree
  - wget
  - watch
  - zlib

mas_apps:
  - { name: EzyCal, id: 1190243926 }
  - { name: Boop, id: 1518425043 }
  - { name: Commander One - file manager, id: 1035236694 }

node_version: 14